# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e53a04b54ca6972910859a5edba1411d"
name = "babeenioverstock: Custom App"
handle = "bovs-custom-app"
application_url = "https://babeeni-26dc9.web.app/app/"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_cart_transforms,read_shipping,write_shipping"

[auth]
redirect_urls = [
  "https://babeeni-26dc9.web.app/api/auth/callback/"
]

[webhooks]
api_version = "2025-01"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "https://babeeni-26dc9.web.app/api/webhooks/"

[app_proxy]
url = "https://babeeni-26dc9.web.app/api/storefront/"
subpath = "bovs-custom-app"
prefix = "apps"

[pos]
embedded = false
